version: '0.1'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server
    volumes:
      - /path/to/host/redis-data:/data  # For Redis data

  app:
    build:
      context: .
      dockerfile: backend/docker/docker_files/Dockerfile_app
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 5000:5000

  django:
    build:
      context: ./backend
      dockerfile: docker/docker_files/Dockerfile_django
    depends_on:
      - redis
    restart: unless-stopped
    #command: python -m manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
  