version: '0.1'
services:

  django:
    build:
      context: ./backend
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    command: python -m manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server
    volumes:
      - /path/to/host/redis-data:/data  # For Redis data
  
  celery:
    build:
      context: .
      dockerfile: backend/docker/docker_files/Dockerfile_celery
    depends_on:
      - redis
      - django
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - ./backend/.env
